import type { Category, Tool } from './types';

export const categories: Category[] = [
  { id: 'all', label: 'All', icon: '✦' },
  { id: 'writing', label: 'Writing', icon: '✍️' },
  { id: 'image-gen', label: 'Image Gen', icon: '🎨' },
  { id: 'video', label: 'Video', icon: '🎬' },
  { id: 'productivity', label: 'Productivity', icon: '⚡' },
  { id: 'marketing', label: 'Marketing', icon: '📈' },
  { id: 'developer', label: 'Developer Tools', icon: '🛠️' },
];

export const tools: Tool[] = [
  // --- WRITING TOOLS ---
  {
    id: 'jasper',
    name: 'Jasper AI',
    logoText: 'JA',
    logoColor: '#8a2be2',
    description: 'Enterprise-grade AI tool designed for long-form blogs, marketing copy, and multi-language social media content matching your brand voice.',
    category: 'writing',
    pricing: 'Free Trial Available',
    url: 'https://jasper.ai',
    deal: 'Exclusive Trial',
    approved: true,
  },
  {
    id: 'copy-ai',
    name: 'Copy.ai',
    logoText: 'Cp',
    logoColor: '#00fa9a',
    description: 'Automated sales content writer and copy helper. Exceptional for quick ad copy, marketing emails, and high-conversion landing pages.',
    category: 'writing',
    pricing: 'Freemium',
    url: 'https://copy.ai',
    approved: true,
  },
  {
    id: 'writesonic',
    name: 'Writesonic',
    logoText: 'Ws',
    logoColor: '#20b2aa',
    description: 'SEO-optimized article writer and paraphraser. Perfect for generating high-ranking articles and marketing outlines in a few seconds.',
    category: 'writing',
    pricing: 'Freemium',
    url: 'https://writesonic.com',
    approved: true,
  },
  {
    id: 'anyword',
    name: 'Anyword',
    logoText: 'Aw',
    logoColor: '#ff7f50',
    description: 'Performance-driven copywriting platform that analyzes your audience data and scores your copy before you hit publish.',
    category: 'writing',
    pricing: 'Free Trial Available',
    url: 'https://anyword.com',
    approved: true,
  },
  {
    id: 'sudowrite',
    name: 'Sudowrite',
    logoText: 'Sd',
    logoColor: '#ff1493',
    description: 'The specialized non-fiction and novel writer AI companion. Helps plot chapters, brainstorm characters, and rewrite draft scenes dynamically.',
    category: 'writing',
    pricing: 'Free Trial Available',
    url: 'https://sudowrite.com',
    approved: true,
  },

  // --- IMAGE GEN TOOLS ---
  {
    id: 'kittl',
    name: 'Kittl Design',
    logoText: 'Kt',
    logoColor: '#d2691e',
    description: 'An advanced vector and design ecosystem packed with robust AI features for creating stunning brand logos, merch layouts, and posters.',
    category: 'image-gen',
    pricing: 'Freemium',
    url: 'https://kittl.com',
    deal: 'Save 20%',
    approved: true,
  },
  {
    id: 'leonardo-ai',
    name: 'Leonardo.ai',
    logoText: 'Le',
    logoColor: '#ffd700',
    description: 'Highly versatile visual generator engineered for video game character designs, production assets, and high-quality concepts.',
    category: 'image-gen',
    pricing: 'Freemium',
    url: 'https://leonardo.ai',
    approved: true,
  },
  {
    id: 'photoroom',
    name: 'Photoroom',
    logoText: 'Pr',
    logoColor: '#4169e1',
    description: 'Premium AI studio for online storefronts and sellers. Effortlessly crop backgrounds and simulate studio product photography snapshots instantly.',
    category: 'image-gen',
    pricing: 'Freemium',
    url: 'https://photoroom.com',
    approved: true,
  },
  {
    id: 'clipdrop',
    name: 'Clipdrop AI',
    logoText: 'Cd',
    logoColor: '#00bfb2',
    description: 'A powerful collection of light AI visual solutions for instant upscaling, uncropping, background deletion, and lightning adjustments.',
    category: 'image-gen',
    pricing: 'Freemium',
    url: 'https://clipdrop.co',
    approved: true,
  },

  // --- VIDEO TOOLS ---
  {
    id: 'heygen',
    name: 'HeyGen Avatars',
    logoText: 'Hg',
    logoColor: '#ff007f',
    description: 'Industry-leading corporate avatar video studio. Generate real talking videos from plain text scripts in hundreds of active voices and languages.',
    category: 'video',
    pricing: 'Free Trial Available',
    url: 'https://heygen.com',
    deal: 'Top Choice',
    approved: true,
  },
  {
    id: 'synthesia',
    name: 'Synthesia AI',
    logoText: 'Sy',
    logoColor: '#1e3a8a',
    description: 'Transform traditional text briefings, technical documentation, or standard guides directly into clear visual avatar-led lecture videos.',
    category: 'video',
    pricing: 'Paid',
    url: 'https://synthesia.io',
    approved: true,
  },
  {
    id: 'invideo-ai',
    name: 'InVideo AI',
    logoText: 'Iv',
    logoColor: '#9333ea',
    description: 'An AI engine that translates text ideas directly into complete, polished horizontal or short YouTube videos with script, overlay clips, and voiceovers.',
    category: 'video',
    pricing: 'Freemium',
    url: 'https://invideo.io',
    approved: true,
  },
  {
    id: 'opus-clip',
    name: 'Opus Clip',
    logoText: 'Oc',
    logoColor: '#f59e0b',
    description: 'Repurpose one single heavy podcast recording or video lecture link into ten ultra-fast viral video clips custom formatted for phone feeds.',
    category: 'video',
    pricing: 'Freemium',
    url: 'https://opus.pro',
    approved: true,
  },

  // --- PRODUCTIVITY TOOLS ---
  {
    id: 'taskade',
    name: 'Taskade AI',
    logoText: 'Tk',
    logoColor: '#10b981',
    description: 'Structured mapping canvas driven by custom autonomous AI agents designed to handle project assignments, workflows, and task tracking.',
    category: 'productivity',
    pricing: 'Freemium',
    url: 'https://taskade.com',
    approved: true,
  },
  {
    id: 'otter-ai',
    name: 'Otter.ai Meetings',
    logoText: 'Ot',
    logoColor: '#2563eb',
    description: 'Smart business meeting log assistant. Tracks web conferences live, transcribes conversations word-for-word, and shares summaries.',
    category: 'productivity',
    pricing: 'Freemium',
    url: 'https://otter.ai',
    approved: true,
  },
  {
    id: 'motion-cal',
    name: 'Motion AI',
    logoText: 'Mo',
    logoColor: '#dc2626',
    description: 'Intelligent digital scheduler tool designed to track custom milestones and plan daily micro-tasks on your calendar entirely automatically.',
    category: 'productivity',
    pricing: 'Free Trial Available',
    url: 'https://usemotion.com',
    approved: true,
  },
  {
    id: 'gamma-app',
    name: 'Gamma App',
    logoText: 'Ga',
    logoColor: '#ec4899',
    description: 'Generate clean presentation files, documents, or responsive webpage designs via natural chat conversations in under a single minute.',
    category: 'productivity',
    pricing: 'Freemium',
    url: 'https://gamma.app',
    deal: 'Highly Popular',
    approved: true,
  },

  // --- MARKETING TOOLS ---
  {
    id: 'canva',
    name: 'Canva Pro',
    logoText: 'Cv',
    logoColor: '#00c4cc',
    description: 'Design anything with drag-and-drop ease. Packed with robust AI solutions to handle template designs, assets, and automated content styling.',
    category: 'marketing',
    pricing: 'Freemium',
    url: 'https://www.canva.com',
    approved: true,
  },
  {
    id: 'adcreative',
    name: 'AdCreative.ai',
    logoText: 'Ad',
    logoColor: '#3b82f6',
    description: 'Artificial intelligence built to generate high-conversion promotional graphic ad layouts, media text lines, and product post variants quickly.',
    category: 'marketing',
    pricing: 'Free Trial Available',
    url: 'https://adcreative.ai',
    approved: true,
  }
];
