import type { Category, Tool } from './types';

export const categories: Category[] = [
  { id: 'all', label: 'All', icon: '✦' },
  { id: 'writing', label: 'Writing', icon: '✍️' },
  { id: 'image-gen', label: 'Image Gen', icon: '🎨' },
  { id: 'video', label: 'Video', icon: '🎬' },
  { id: 'productivity', label: 'Productivity', icon: '⚡' },
  { id: 'marketing', label: 'Marketing', icon: '📈' },
  { id: 'developer', label: 'Developer Tools', icon: '🛠️' },
];

export const tools: Tool[] = [
  // --- WRITING TOOLS (1-10) ---
  {
    id: 'jasper',
    name: 'Jasper AI',
    logoText: 'JA',
    logoColor: '#8a2be2',
    description: 'Enterprise-grade AI tool designed for long-form blogs, marketing copy, and multi-language social media content matching your brand voice.',
    category: 'writing',
    pricing: 'Free Trial Available',
    url: 'https://jasper.ai',
    deal: 'Exclusive Trial',
    approved: true,
  },
  {
    id: 'copy-ai',
    name: 'Copy.ai',
    logoText: 'Cp',
    logoColor: '#00fa9a',
    description: 'Automated sales content writer and copy helper. Exceptional for quick ad copy, marketing emails, and high-conversion landing pages.',
    category: 'writing',
    pricing: 'Freemium',
    url: 'https://copy.ai',
    approved: true,
  },
  {
    id: 'writesonic',
    name: 'Writesonic',
    logoText: 'Ws',
    logoColor: '#20b2aa',
    description: 'SEO-optimized article writer and paraphraser. Perfect for generating high-ranking articles and marketing outlines in a few seconds.',
    category: 'writing',
    pricing: 'Freemium',
    url: 'https://writesonic.com',
    approved: true,
  },
  {
    id: 'anyword',
    name: 'Anyword',
    logoText: 'Aw',
    logoColor: '#ff7f50',
    description: 'Performance-driven copywriting platform that analyzes your audience data and scores your copy before you hit publish.',
    category: 'writing',
    pricing: 'Free Trial Available',
    url: 'https://anyword.com',
    approved: true,
  },
  {
    id: 'sudowrite',
    name: 'Sudowrite',
    logoText: 'Sd',
    logoColor: '#ff1493',
    description: 'The specialized non-fiction and novel writer AI companion. Helps plot chapters, brainstorm characters, and rewrite draft scenes dynamically.',
    category: 'writing',
    pricing: 'Free Trial Available',
    url: 'https://sudowrite.com',
    approved: true,
  },
  {
    id: 'rytr',
    name: 'Rytr',
    logoText: 'Ry',
    logoColor: '#f59e0b',
    description: 'An affordable, ultra-fast AI writing assistant for generating catchy social media captions, short blog intros, and business email formats.',
    category: 'writing',
    pricing: 'Freemium',
    url: 'https://rytr.me',
    approved: true,
  },
  {
    id: 'wordtune',
    name: 'Wordtune',
    logoText: 'Wt',
    logoColor: '#3b82f6',
    description: 'An AI-powered sentence rewriter that checks your tone, expands short sentences, or shortens long paragraphs to match a professional voice.',
    category: 'writing',
    pricing: 'Freemium',
    url: 'https://wordtune.com',
    approved: true,
  },
  {
    id: 'frase',
    name: 'Frase',
    logoText: 'Fr',
    logoColor: '#6366f1',
    description: 'AI-driven content research and optimization platform that analyzes top competitor articles on Google to outline your perfect blog structure.',
    category: 'writing',
    pricing: 'Free Trial Available',
    url: 'https://frase.io',
    approved: true,
  },
  {
    id: 'scalenut',
    name: 'Scalenut SEO',
    logoText: 'Sn',
    logoColor: '#10b981',
    description: 'An all-in-one content marketing workspace that helps you plan high-traffic content keywords, write articles, and fix SEO optimization scores.',
    category: 'writing',
    pricing: 'Free Trial Available',
    url: 'https://scalenut.com',
    approved: true,
  },
  {
    id: 'grammarly',
    name: 'Grammarly AI',
    logoText: 'Gr',
    logoColor: '#11a87e',
    description: 'The world-standard grammar editor with integrated AI assistance to dynamically rewrite text for clarity, accuracy, and tone enhancement.',
    category: 'writing',
    pricing: 'Freemium',
    url: 'https://grammarly.com',
    approved: true,
  },

  // --- IMAGE GEN TOOLS (11-18) ---
  {
    id: 'kittl',
    name: 'Kittl Design',
    logoText: 'Kt',
    logoColor: '#d2691e',
    description: 'An advanced vector and design ecosystem packed with robust AI features for creating stunning brand logos, merch layouts, and posters.',
    category: 'image-gen',
    pricing: 'Freemium',
    url: 'https://kittl.com',
    deal: 'Save 20%',
    approved: true,
  },
  {
    id: 'leonardo-ai',
    name: 'Leonardo.ai',
    logoText: 'Le',
    logoColor: '#ffd700',
    description: 'Highly versatile visual generator engineered for video game character designs, production assets, and high-quality concepts.',
    category: 'image-gen',
    pricing: 'Freemium',
    url: 'https://leonardo.ai',
    approved: true,
  },
  {
    id: 'photoroom',
    name: 'Photoroom',
    logoText: 'Pr',
    logoColor: '#4169e1',
    description: 'Premium AI studio for online storefronts and sellers. Effortlessly crop backgrounds and simulate studio product photography snapshots instantly.',
    category: 'image-gen',
    pricing: 'Freemium',
    url: 'https://photoroom.com',
    approved: true,
  },
  {
    id: 'clipdrop',
    name: 'Clipdrop AI',
    logoText: 'Cd',
    logoColor: '#00bfb2',
    description: 'A powerful collection of light AI visual solutions for instant upscaling, uncropping, background deletion, and lightning adjustments.',
    category: 'image-gen',
    pricing: 'Freemium',
    url: 'https://clipdrop.co',
    approved: true,
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    logoText: 'Mj',
    logoColor: '#8b5cf6',
    description: 'Top-tier realistic prompt-to-art generation system operating on Discord. Unrivaled clarity for creating concept environments and artistic elements.',
    category: 'image-gen',
    pricing: 'Paid',
    url: 'https://midjourney.com',
    approved: true,
  },
  {
    id: 'stockimg',
    name: 'Stockimg.ai',
    logoText: 'Si',
    logoColor: '#ec4899',
    description: 'Specialized generation interface custom tailored to produce gorgeous digital book covers, app icons, and stock background textures.',
    category: 'image-gen',
    pricing: 'Freemium',
    url: 'https://stockimg.ai',
    approved: true,
  },
  {
    id: 'adobe-firefly',
    name: 'Adobe Firefly',
    logoText: 'Ff',
    logoColor: '#ff0000',
    description: 'Commercially completely safe generative AI suite by Adobe, engineered directly for generative background filling and premium text layouts.',
    category: 'image-gen',
    pricing: 'Freemium',
    url: 'https://adobe.com',
    approved: true,
  },
  {
    id: 'playground-ai',
    name: 'Playground AI',
    logoText: 'Pl',
    logoColor: '#0ea5e9',
    description: 'Free browser canvas tool allowing detailed element editing, composition masking, and mixed vector image creation using raw descriptive inputs.',
    category: 'image-gen',
    pricing: 'Freemium',
    url: 'https://playground.com',
    approved: true,
  },

  // --- VIDEO TOOLS (19-26) ---
  {
    id: 'heygen',
    name: 'HeyGen Avatars',
    logoText: 'Hg',
    logoColor: '#ff007f',
    description: 'Industry-leading corporate avatar video studio. Generate real talking videos from plain text scripts in hundreds of active voices and languages.',
    category: 'video',
    pricing: 'Free Trial Available',
    url: 'https://heygen.com',
    deal: 'Top Choice',
    approved: true,
  },
  {
    id: 'synthesia',
    name: 'Synthesia AI',
    logoText: 'Sy',
    logoColor: '#1e3a8a',
    description: 'Transform traditional text briefings, technical documentation, or standard guides directly into clear visual avatar-led lecture videos.',
    category: 'video',
    pricing: 'Paid',
    url: 'https://synthesia.io',
    approved: true,
  },
  {
    id: 'invideo-ai',
    name: 'InVideo AI',
    logoText: 'Iv',
    logoColor: '#9333ea',
    description: 'An AI engine that translates text ideas directly into complete, polished horizontal or short YouTube videos with script, overlay clips, and voiceovers.',
    category: 'video',
    pricing: 'Freemium',
    url: 'https://invideo.io',
    approved: true,
  },
  {
    id: 'opus-clip',
    name: 'Opus Clip',
    logoText: 'Oc',
    logoColor: '#f59e0b',
    description: 'Repurpose one single heavy podcast recording or video lecture link into ten ultra-fast viral video clips custom formatted for phone feeds.',
    category: 'video',
    pricing: 'Freemium',
    url: 'https://opus.pro',
    approved: true,
  },
  {
    id: 'runway',
    name: 'Runway Gen-3',
    logoText: 'Rw',
    logoColor: '#f43f5e',
    description: 'Cinematic dynamic prompt-to-video generation software that yields breathtaking camera panning, realistic physics, and movement simulations.',
    category: 'video',
    pricing: 'Free Trial Available',
    url: 'https://runwayml.com',
    approved: true,
  },
  {
    id: 'descript',
    name: 'Descript Editor',
    logoText: 'Ds',
    logoColor: '#047857',
    description: 'Mind-blowing editing interface allowing you to cut or patch sound clips and videos simply by deleting words directly inside an auto-generated text document.',
    category: 'video',
    pricing: 'Freemium',
    url: 'https://descript.com',
    approved: true,
  },
  {
    id: 'veed-io',
    name: 'Veed.io Studio',
    logoText: 'Vd',
    logoColor: '#3b82f6',
    description: 'Cloud video configuration tool featuring stunning auto-transcriptions, glowing voice subtitles, and direct frame resizing shortcuts for social apps.',
    category: 'video',
    pricing: 'Freemium',
    url: 'https://veed.io',
    approved: true,
  },
  {
    id: 'pictory',
    name: 'Pictory AI',
    logoText: 'Pc',
    logoColor: '#06b6d4',
    description: 'Extract summarized visual clips and articles out of massive audio webinars or zoom records to deploy fast educational or commercial layouts easily.',
    category: 'video',
    pricing: 'Free Trial Available',
    url: 'https://pictory.ai',
    approved: true,
  },
     // --- PRODUCTIVITY TOOLS (27-34) ---
  {
    id: 'taskade',
    name: 'Taskade AI',
    logoText: 'Tk',
    logoColor: '#10b981',
    description: 'Structured mapping canvas driven by custom autonomous AI agents designed to handle project assignments, workflows, and task tracking.',
    category: 'productivity',
    pricing: 'Freemium',
    url: 'taskade.com',
    approved: true,
  },
  {
    id: 'otter-ai',
    name: 'Otter.ai Meetings',
    logoText: 'Ot',
    logoColor: '#2563eb',
    description: 'Smart business meeting log assistant. Tracks web conferences live, transcribes conversations word-for-word, and shares summaries.',
    category: 'productivity',
    pricing: 'Freemium',
    url: 'https://otter.ai',
    approved: true,
  },
  {
    id: 'motion-cal',
    name: 'Motion AI',
    logoText: 'Mo',
    logoColor: '#dc2626',
    description: 'Intelligent digital scheduler tool designed to track custom milestones and plan daily micro-tasks on your calendar entirely automatically.',
    category: 'productivity',
    pricing: 'Free Trial Available',
    url: 'usemotion.com',
    approved: true,
  },
  {
    id: 'gamma-app',
    name: 'Gamma App',
    logoText: 'Ga',logoColor: '#ec4899',
    description: 'Generate clean presentation files, documents, or responsive webpage designs via natural chat conversations in under a single minute.',
    category: 'productivity',
    pricing: 'Freemium',
    url: 'https://gamma.app',
    deal: 'Highly Popular',
    approved: true,
  },
  {
    id: 'notion',
    name: 'Notion AI',
    logoText: 'Nt',logoColor: '#1f2937',
    description: 'The industry-standard personal base workspace connected with integrated system engines to summarize tables and expand notes instantly.',
    category: 'productivity',
    pricing: 'Freemium',
    url: 'notion.so',
    approved: true,
  },
  {
    id: 'sanebox',
    name: 'SaneBox Email',
    logoText: 'Sb',
    logoColor: '#a855f7',
    description: 'Intelligent mail manager that monitors your mailbox to organize priority records, sort newsletters, and wipe junk scripts autonomously.',
    category: 'productivity',
    pricing: 'Free Trial Available',
    url: 'sanebox.com',
    approved: true,
  },
  {
    id: 'beautiful-ai',
    name: 'Beautiful.ai',
    logoText: 'Bf',
    logoColor: '#14b8a6',
    description: 'Intelligent business presentation slides creator that auto-adjusts chart frame grids and grid proportions as you type raw input rows.',
    category: 'productivity',
    pricing: 'Free Trial Available',
    url: 'beautiful.ai',
    approved: true,
  },
  {
    id: 'tome',
    name: 'Tome Canvas',
    logoText: 'To',
    logoColor: '#ef4444',
    description: 'Fluid data presentation interface that auto-constructs complex technical descriptions, summaries, and graphical data representations instantly.',
    category: 'productivity',
    pricing: 'Freemium',
    url: 'https://tome.app',
    approved: true,
  },
      // --- MARKETING TOOLS (35-42) ---
  {
    id: 'canva',
    name: 'Canva Pro',
    logoText: 'Cv',
    logoColor: '#00c4cc',
    description: 'Design anything with drag-and-drop ease. Packed with robust AI solutions to handle template designs, assets, and automated content styling.',
    category: 'marketing',
    pricing: 'Freemium',
    url: 'canva.com',
    approved: true,
  },
  {
    id: 'adcreative',
    name: 'AdCreative.ai',
    logoText: 'Ad',
    logoColor: '#3b82f6',
    description: 'Artificial intelligence built to generate high-conversion promotional graphic ad layouts, media text lines, and product post variants quickly.',
    category: 'marketing',
    pricing: 'Free Trial Available',
    url: 'adcreative.ai',
    approved: true,
  },
  {
    id: 'semrush',
    name: 'Semrush AI',
    logoText: 'Sr',
    logoColor: '#ff6b00',
    description: 'Premium keyword tracking tracking system integrated with text modules to map business growth paths and optimize website SEO elements.',
    category: 'marketing',
    pricing: 'Free Trial Available',
    url: 'semrush.com',
    approved: true,
  },
  {
    id: 'surfer-seo',
    name: 'Surfer SEO',
    logoText: 'Sf',
    logoColor: '#ea580c',
    description: 'Advanced real-time content ranking evaluation system that instructs your text layouts on exact word patterns to clear target Google structures.',
    category: 'marketing',
    pricing: 'Free Trial Available',
    url: 'https://surferseo.com',
    approved: true,
  },
  {
    id: 'feedly',
    name: 'Feedly Leo',
    logoText: 'Fd',
    logoColor: '#16a34a',
    description: 'An evaluation board prioritizing raw industry web links, trend keywords, and media assets to bundle technical tracking reports instantly.',
    category: 'marketing',
    pricing: 'Freemium',
    url: 'https://feedly.com',
    approved: true,
  },
  {
    id: 'buzzsumo',
    name: 'BuzzSumo AI',
    logoText: 'Bs',
    logoColor: '#2563eb',
    description: 'Content tracking framework calculating viral statistics across target social nodes to discover high-traction content structures matching fields.',
    category: 'marketing',
    pricing: 'Free Trial Available',
    url: 'https://buzzsumo.com',
    approved: true,
  },
  {
    id: 'munch-ai',
    name: 'GetMunch AI',
    logoText: 'Mn',
    logoColor: '#4f46e5',
    description: 'Automatically analyzes massive raw landscape recordings to extract clips containing strong conversational parameters matched for micro-feeds.',
    category: 'marketing',
    pricing: 'Free Trial Available',
    url: 'getmunch.com',
    approved: true,
  },
  {
    id: 'smartlead',
    name: 'Smartlead.ai',
    logoText: 'Sl',
    logoColor: '#7c3aed',
    description: 'Scale complex outreach campaigns through independent automation boxes handling cold mailing sequences matching business profiles securely.',
    category: 'marketing',
    pricing: 'Free Trial Available',
    url: 'smartlead.ai',
    approved: true,
  },
      // --- DEVELOPER TOOLS (43-50) ---
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    logoText: 'Co',
    logoColor: '#6e7681',
    description: 'Your AI pair programmer. Autocompletes code, generates functions, and explains bugs right inside your editor.',
    category: 'developer',
    pricing: 'Free Trial Available',
    url: 'github.com',approved: true,
  },
  {
    id: 'replit-agent',
    name: 'Replit Agent',
    logoText: 'Ra',
    logoColor: '#f43f5e',
    description: 'An automated coding companion workspace capable of building full backend arrays and deploying servers entirely from natural chat conversations.',
    category: 'developer',
    pricing: 'Free Trial Available',
    url: 'https://replit.com',
    approved: true,
  },
  {
    id: 'cursor-editor',
    name: 'Cursor AI',
    logoText: 'Cu',
    logoColor: '#38bdf8',
    description: 'A premium development workspace fork of VS Code engineered to interpret file structures, handle mass script adjustments, and generate code rows.',
    category: 'developer',
    pricing: 'Freemium',
    url: 'cursor.com',
    approved: true,
  },
  {
    id: 'blackbox',
    name: 'Blackbox AI',
    logoText: 'Bb',
    logoColor: '#fbbf24',
    description: 'Ultra-fast auto-completion search engine built specifically for developers to find code syntax rows directly from natural text inputs.',
    category: 'developer',
    pricing: 'Freemium',
    url: 'useblackbox.io',
    approved: true,
  },
  {
    id: 'tabnine',
    name: 'Tabnine',
    logoText: 'Tb',
    logoColor: '#ec4899',
    description: 'Secure, local-running developer code autocomplete logic container ideal for protecting enterprise files while speeding script row additions.',
    category: 'developer',
    pricing: 'Freemium',
    url: 'tabnine.com',
    approved: true,
  },
  {
    id: 'v0-dev',
    name: 'v0.dev by Vercel',
    logoText: 'V0',
    logoColor: '#000000',
    description: 'Generates beautiful, fully structured interface components and visual styling code layers directly from standard text layouts.',
    category: 'developer',
    pricing: 'Freemium',
    url: 'https://v0.dev',
    approved: true,
  },
  {
    id: 'mintlify',
    name: 'Mintlify',
    logoText: 'Mt',
    logoColor: '#059669',
    description: 'Scans your raw software application files to auto-build premium, gorgeous technical guide manuals and developer integration wikis instantly.',
    category: 'developer',
    pricing: 'Freemium',
    url: 'https://mintlify.com',
    approved: true,
  },
  {
    id: 'phind',
    name: 'Phind Engine',
    logoText: 'Ph',
    logoColor: '#6366f1',
    description: 'Search architecture optimized to read developer inquiries, study code lines, and render debug advice linked to frameworks.',
    category: 'developer',
    pricing: 'Freemium',
    url: 'phind.com',
    approved: true,
  },
  {
    id: 'sponsored-slot-placeholder',
    name: '🚀 Sponsor This Slot',
    logoText: '★',
    logoColor: '#ff6b00',
    description: 'Want your AI tool or software featured right here at the top of NovaTools Hub to reach thousands of active creators? Click below to secure this premium ad placement instantly.',
    category: 'developer',
    pricing: 'Sponsored Placement',
    url: 'mailto:mahakaalstudio.dev@gmail.com',
    deal: 'Spot Available',
    approved: true,
  }

];